containers/pax-exam-container-native/src/main/java/org/ops4j/pax/exam/nat/internal/NativeTestContainer.java, core/pax-exam/src/main/java/org/ops4j/pax/exam/FrameworkEventUtils.java
Add logging of framework events; this has the effect of revealing Equinox wiring errors which otherwise remain mysterious. Also make it possible to create more useful subclasses of NativeTestContainer by making two things protected and adding a hook function between framework init and bundle load.
Provide a utility to render framework event types as strings.
=> PAXEXAM-726: more information in log from framework events;

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafPropertiesFile.java
make the exception more precise e.g. if file could not be found
=> [PAXEXAM-753] add cause to exception

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafTestContainer.java, core/pax-exam/src/main/java/org/ops4j/pax/exam/CoreOptions.java, core/pax-exam/src/main/java/org/ops4j/pax/exam/options/extra/EnvironmentOption.java, itest/karaf/src/it/regression-karaf/src/test/java/org/ops4j/pax/exam/regression/karaf/EnvironmentOptionTest.java
This commit adds option to Pax Exam to add process environment variables
to the contaner. Implemented for Karaf only.
=> PAXEXAM-804 Add process environment option to Pax Exam

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/runner/KarafEmbeddedRunner.java
When I test karaf in enbeded mode, KarafEmbeddedRunner cannot find main libs.
Can you approve this path ?
=> Cannot found jar file on windows : use separtor in system insteadof '/'

containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/AbstractKarafTestContainerITest.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/Karaf3TestContainerITest.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/Karaf4TestContainerITest.java
it was actually completely broken; as karafVersion() does not specify
which version to download, just adapt the start up; the frameworkUrl)(
needs a version() to choose between Karaf 3 & 4.. also can't be static.
Changed from ignore.ignoreLocalConsole().startRemoteShell() to
startLocalConsole().ignoreRemoteShell() instead, as it's handy to see
the Karaf banner on start up to recognize the version; and the remote
is not needed.
Also the versions were actually inavertedly inverted between *3/4Test* ;)
=> Fix Karaf[34]TestContainerITest

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafTestContainer.java, core/pax-exam-container-rbc-client/src/main/java/org/ops4j/pax/exam/rbc/client/intern/RemoteBundleContextClientImpl.java
this appears e.g. on Fedora Linux on a laptop with two network adapters
(WiFi and wired Ethernet), if the hostname is not listed in /etc/hosts,
due to use of LocateRegistry -> InetAddress.getLocalHost(), but can also
occcur under other network configurations.
This change fixes the problem in pax-exam-container-karaf.  For
pax-exam-container-forked, another change in Pax Swissbox is required
(coming up next).
see also
http://blog2.vorburger.ch/2017/04/java-local-rmi-using-jdks-inetaddress.html
for more background, and
https://bugs.opendaylight.org/show_bug.cgi?id=8176 for original error.
=> [PAXEXAM-740] Fix NoRouteToHostException RMI issue for Karaf

core/pax-exam-spi/src/main/java/org/ops4j/pax/exam/spi/reactors/ReactorManager.java
Just for clearer stack traces, see discussion in JIRA.
=> [PAXEXAM-811] ReactorManager skip reflect.InvocationTargetException

containers/pax-exam-container-forked/pom.xml, containers/pax-exam-container-forked/src/main/java/org/ops4j/pax/exam/forked/ForkedFrameworkFactory.java
this appears e.g. on Fedora Linux on a laptop with two network adapters
(WiFi and wired Ethernet), if the hostname is not listed in /etc/hosts,
due to use of LocateRegistry -> InetAddress.getLocalHost(), but can also
occur under other network configurations.
This change fixes the problem in pax-exam-container-forked; but [also
needed changes in Pax Swissbox](https://github.com/ops4j/org.ops4j.pax.swissbox/pull/4), thus the uprade to a new version.
see also
http://blog2.vorburger.ch/2017/04/java-local-rmi-using-jdks-inetaddress.html
=> [PAXEXAM-740] Fix NoRouteToHostException RMI issue for forked

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafTestContainer.java, containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/options/KarafDistributionOption.java, containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/options/libraries/OverrideJUnitBundlesOption.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/AbstractKarafTestContainerITest.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/ValidateDefaultJUnitBundles.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/ValidateOverridingJUnitBundles.java, features/src/main/resources/features.xml
This change allows test libraries to be optionally switched out for customised versions. In the provided test this is from the pax-exam's own wrapped hamcrest-core to the servicemix wrapped hamcrest-all, exposing access to hamcrest-library.
This PR would supersede #35.
=> [PAXEXAM-723] Allow for overriding JUnit related bundles within the Karaf container

itest/cdi/pom.xml, itest/cdi/src/it/regression-cdi-invalid/pom.xml, itest/cdi/src/it/regression-cdi-probe/pom.xml, itest/cdi/src/it/regression-cdi-testng/pom.xml, itest/cdi/src/it/regression-cdi/pom.xml, itest/cdi/src/it/regression-deltaspike/pom.xml, itest/javaee/pom.xml, itest/javaee/src/it/regression-javaee-data/pom.xml, itest/javaee/src/it/regression-javaee-jboss-module/pom.xml, itest/javaee/src/it/regression-javaee-moviefun/pom.xml, itest/javaee/src/it/regression-javaee-testng/pom.xml, itest/javaee/src/it/regression-javaee-userprobe/pom.xml, itest/javaee/src/it/regression-javaee/pom.xml, itest/karaf/pom.xml, itest/karaf/src/it/regression-karaf/pom.xml, itest/osgi/pom.xml, itest/osgi/src/it/regression-maven-plugin/pom.xml, itest/osgi/src/it/regression-multi/pom.xml, itest/osgi/src/it/regression-plumbing/pom.xml, itest/osgi/src/it/regression-testng-perclass/pom.xml, itest/osgi/src/it/regression-testng/pom.xml, itest/pom.xml, itest/web/pom.xml, itest/web/src/it/regression-web-spring-userprobe/pom.xml, itest/web/src/it/regression-web-spring/pom.xml, itest/web/src/it/regression-web/pom.xml
This allows the integration tests to be run against the current tree. They still fail at the JavaEE tests.
=> [PAXEXAM-816] Update itest POMs to 4.10.1-SNAPSHOT

circle.yml
due to https://issues.apache.org/jira/browse/MDEP-516
(maybe also related to https://issues.apache.org/jira/browse/MDEP-82)
This seems to be how most projects found e.g. on GitHub
deal with this problem (search for circle.yml files containing
"dependency:go-offline", and many will have something like this).
=> Fix CirleCI's dependency:go-offline on pom.xml version number upgrades

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/JavaVersionUtil.java, containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafTestContainer.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/internal/JavaVersionUtilTest.java
The goal of this PR is to make Java major detection more solid.
Early access builds have the following pattern MAJOR-ea (typically 11-ea).
I was unable to log in on your issue tracker to create a JIRA and affect it to the commit message, is it open to external contributors?
=> Make the Java major version detection for Karaf more solid

core/pax-exam-spi/src/main/java/org/ops4j/pax/exam/spi/PaxExamRuntime.java
Backport of the fix for PAXEXAM-887 towards the 4.x branch.
=> Backport: [PAXEXAM-887] Do not deploy compendium bundle

containers/pax-exam-container-forked/src/main/java/org/ops4j/pax/exam/forked/ForkedFrameworkFactory.java, containers/pax-exam-container-forked/src/main/java/org/ops4j/pax/exam/forked/ForkedTestContainer.java, containers/pax-exam-container-forked/src/test/java/org/ops4j/pax/exam/forked/ForkedFrameworkFactoryTest.java, containers/pax-exam-container-forked/src/test/java/org/ops4j/pax/exam/forked/ForkedTestContainerFactoryTest.java, containers/pax-exam-container-forked/src/test/java/org/ops4j/pax/exam/forked/SystemPropertyRunnable.java, core/pax-exam/src/main/java/org/ops4j/pax/exam/Constants.java
Make socket-based communication for invoker and RMI of forked container configurable through system properties.
If you agree to change some method visibility I could test using mockito otherwise I should use PowerMockito to enable mock of private methods and final classes.
=> [PAXEXAM-926] RMI port range is not configurable for forked container

core/pax-exam-invoker-junit/src/main/java/org/ops4j/pax/exam/invoker/junit/internal/JUnitProbeInvoker.java, core/pax-exam-invoker-junit/src/test/java/org/ops4j/pax/exam/invoker/junit/internal/CustomFilterSimpleTestHidden.java, core/pax-exam-invoker-junit/src/test/java/org/ops4j/pax/exam/invoker/junit/internal/JUnitProbeInvokerTest.java, core/pax-exam/src/main/java/org/ops4j/pax/exam/TestDescription.java, core/pax-exam/src/main/java/org/ops4j/pax/exam/TestFilter.java, core/pax-exam/src/test/java/org/ops4j/pax/exam/TestDescriptorTest.java, core/pax-exam/src/test/java/org/ops4j/pax/exam/TestFilterTest.java, drivers/pax-exam-junit4/src/main/java/org/ops4j/pax/exam/junit/DriverExtension.java, drivers/pax-exam-junit4/src/main/java/org/ops4j/pax/exam/junit/ExtensibleRunner.java, drivers/pax-exam-junit4/src/main/java/org/ops4j/pax/exam/junit/RunnerExtension.java
We are using the latest beta 5.0 to obtain the support for Before/After Class.
When we want to run exactly a specific test method of a test suite from eclipse IDE for example we got that all test are executed. The same issue happens in maven when the rerun feature is enabled. The point is that when we got a failure all tests in the test suite are re-executed. This means increase build time and sometimes the failure of test flaky that was passed on the first run.
The root cause is that the list of filtered out methods are not passed when the OSGi service junit invoker is called.
Unfortunally when a filter (I mean a simple method descriptor filter) is applied to the JUnitCore instance it apply this filter internally saving the filtered list of descriptor that must be executed. This internal …
=> [PAXEXAM-930] Any filter applied to the JUnitCore is honored the unit tests are invoker in the container

drivers/pax-exam-junit4/src/main/java/org/ops4j/pax/exam/junit/impl/ParameterizedFrameworkMethod.java, drivers/pax-exam-junit4/src/main/java/org/ops4j/pax/exam/junit/impl/ParameterizedProbeRunner.java, itest/karaf/src/it/regression-karaf/src/test/java/org/ops4j/pax/exam/regression/karaf/ParameterizedTest.java
The parameterized test runner is unable to evaluate parameter values when creating the test names. Adding support for this would add clarity to the tests being executed. https://github.com/junit-team/junit4/wiki/parameterized-tests
This topic was discussed briefly in https://ops4j1.jira.com/browse/PAXEXAM-674 . I tried to make a separate issue but did not have account access to do so.
=> Add support for parameterized named tests

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafTestContainer.java
Currently Karaf startup files include adding lib/jdk9plus to the classpath if the jdk is beyond 8.  Libraries that require JavaEE libraries that have been removed in Java 11 fail without this.
https://github.com/apache/karaf/blob/43207e4cfcd2619483a84da90dd78077c4bdd9d7/assemblies/features/base/src/main/filtered-resources/resources/bin/karaf.bat#L318
=> Add jdk9plus lib directory to karaf classpath.

containers/pax-exam-container-forked/src/test/java/org/ops4j/pax/exam/forked/ForkedFrameworkFactoryTest.java, containers/pax-exam-container-forked/src/test/java/org/ops4j/pax/exam/forked/ForkedTestContainerFactoryTest.java, containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/runner/KarafEmbeddedRunner.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/AbstractKarafTestContainerITest.java, containers/pax-exam-container-karaf/src/test/java/org/ops4j/pax/exam/karaf/container/Karaf4EmbeddedTestContainerITest.java
Embedded runner does not isolate test classloader (jvm) from OSGi container leading to not matching classes (at least in felix).
This PR ensures the test classloader only leaks JVM classes.
Side note: I got some issues running tests, I fixed a few but Karaf ones don't run for me with NoClassDefFoundError in karaf options - even before the diff, not sure what I did wrong.
=> fixing karaf embedded runner

pom/pom.xml
This realigns the version with pax-web, so that exam and web can be used
together out of the box with an empty mvn repo.
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>
=> Bump atinject to 1.2

containers/pax-exam-container-karaf/src/main/java/org/ops4j/pax/exam/karaf/container/internal/KarafTestContainer.java
Closing the streams fixes Karaf integration tests on Windows.
=> [PAXEXAM-1027] Close streams in KarafTestContainer
